/// HIVE TYPES
const int HIVE_TYPE_ID_ACTOR_VO = 1;
const int HIVE_TYPE_ID_BASE_ACTOR_VO = 2;
const int HIVE_TYPE_ID_COLLECTION_VO = 3;
const int HIVE_TYPE_ID_CREDIT_VO = 4;
const int HIVE_TYPE_ID_DATE_V0 = 5;
const int HIVE_TYPE_ID_GENRE_VO = 6;
const int HIVE_TYPE_ID_MOVIE_VO = 7;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 8;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO = 9;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 10;

const int HIVE_TYPE_ID_BANNER_VO = 11;
const int HIVE_TYPE_ID_CITY_VO = 12;
const int HIVE_TYPE_ID_PAYMENT_VO = 13;

const int HIVE_TYPE_ID_USER_DATA_VO = 14;
const int HIVE_TYPE_ID_USER_DATA_TOKEN_VO = 15;

const int HIVE_TYPE_ID_SNACK_CATEGORY_VO = 16;
const int HIVE_TYPE_ID_SNACK_VO = 17;
const int HIVE_TYPE_ID_CATEGORIES_SNACK_VO = 18;

const int HIVE_TYPE_ID_CONFIG_DATA_VO = 19;
const int HIVE_TYPE_ID_GET_CONFIG_RESPONSE_VO = 20;

const int HIVE_TYPE_ID_CINEMA_VO = 21;
const int HIVE_TYPE_ID_CINEMA_FACILITIES_VO = 22;
const int HIVE_TYPE_ID_GET_CINEMA_RESPONSE_VO = 23;

const int HIVE_TYPE_ID_CINEMA_DATA_VO = 24;
const int HIVE_TYPE_ID_TIMESLOTS_VO = 25;
const int HIVE_TYPE_ID_CINEMA_TIMESLOTS_RESPONSE = 26;

/// Box names
const String BOX_NAME_ACTOR_VO = "BOX_NAME_ACTOR_VO";
const String BOX_NAME_BASE_ACTOR_VO = "BOX_NAME_BASE_ACTOR_VO";
const String BOX_NAME_COLLECTION_VO = "BOX_NAME_COLLECTION_VO";
const String BOX_NAME_CREDIT_VO = "BOX_NAME_CREDIT_VO";
const String BOX_NAME_DATE_VO = "BOX_NAME_DATE_VO";
const String BOX_NAME_GENRE_VO = "BOX_NAME_GENRE_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_PRODUCTION_COMPANY_VO = "BOX_NAME_PRODUCTION_COMPANY_VO";
const String BOX_NAME_PRODUCTION_COUNTRY_VO = "BOX_NAME_PRODUCTION_COUNTRY_VO";
const String BOX_NAME_SPOKEN_LANGUAGE_VO = "BOX_NAME_SPOKEN_LANGUAGE_VO";

const String BOX_NAME_BANNER_VO = "BOX_NAME_BANNER_VO";
const String BOX_NAME_CITY_VO = "BOX_NAME_CITY_VO";
const String BOX_NAME_PAYMENT_VO = "BOX_NAME_PAYMENT_VO";
const String BOX_NAME_USER_DATA_VO = "BOX_NAME_USER_DATA_VO";
const String BOX_NAME_USER_DATA_TOKEN_VO = "BOX_NAME_USER_DATA_TOKEN_VO";
const String BOX_NAME_SNACK_CATEGORY_VO = "BOX_NAME_SNACK_CATEGORY_VO";
const String BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
const String BOX_NAME_CATEGORIES_SNACK_VO = "BOX_NAME_CATEGORIES_SNACK_VO";

const String BOX_NAME_CONFIG_DATA_VO = "BOX_NAME_CONFIG_DATA_VO";
const String BOX_NAME_GET_CONFIG_RESPONSE_VO = "BOX_NAME_GET_CONFIG_RESPONSE_VO";
const String BOX_NAME_CINEMA_VO = "BOX_NAME_CINEMA_VO";
const String BOX_NAME_CINEMA_FACILITIES_VO = "BOX_NAME_CINEMA_FACILITIES_VO";
const String BOX_NAME_GET_CINEMA_RESPONSE_VO = "BOX_NAME_CINEMA_RESPONSE_VO";

const String BOX_NAME_CINEMA_DATA_VO = "BOX_NAME_CINEMA_DATA_VO";
const String BOX_NAME_TIMESLOTS_VO = "BOX_NAME_TIMESLOTS_VO";
const String BOX_NAME_CINEMA_TIMESLOTS_RESPONSE = "BOX_NAME_CINEMA_TIMESLOTS_RESPONSE";
